<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>compatibility.fixture</groupId>
    <artifactId>api-compatibility-fixture</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>com.github.siom79.japicmp</groupId>
                <artifactId>japicmp-maven-plugin</artifactId>
                <version>0.26.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.groovy</groupId>
                        <artifactId>groovy-jsr223</artifactId>
                        <version>4.0.30</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <oldVersion>
                        <file>
                            <path>${old.jar}</path>
                        </file>
                    </oldVersion>
                    <newVersion>
                        <file>
                            <path>${new.jar}</path>
                        </file>
                    </newVersion>
                    <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
                    <breakBuildOnSourceIncompatibleModifications>true</breakBuildOnSourceIncompatibleModifications>
                    <parameter>
                        <onlyModified>true</onlyModified>
                        <postAnalysisScript>${project.basedir}/../../scripts/japicmp-annotation-default-compatibility.groovy</postAnalysisScript>
                    </parameter>
                </configuration>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>cmp</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
